### ISSUE TITLE
ThroughputRunChart shows all the data from the last 4 years - please fix this

### ISSUE THREAD

**Issue by ZylkaGreger** [LetPeopleWork/FlowMetricsCSV#1]
[config.json](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13928692/config.json)
[Query_240112_1605.csv](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13928693/Query_240112_1605.csv)

**Comment by ZylkaGreger** [comment]
![Throughput](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/6fa0e49b-fe15-42bd-ba0f-45796a744d0f)

There is more

**Comment by ZylkaGreger** [comment]
![ThroughputRunChart](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/096b03f3-962c-4efc-b5c7-ec7dd10aec61)

**Comment by huserben** [comment]
Fixed in 8ddb9678dab350cfafd82e2899fe3e93495b4e28
