### ISSUE TITLE
Work started and closed does not fit the data provided in the csv.

### ISSUE THREAD

**Issue by ZylkaGreger** [LetPeopleWork/FlowMetricsCSV#2]
there is probably also something wrong with the Throughput chart - the closed date 27.12. is not being shown
[Query_240115_1632.csv](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13940654/Query_240115_1632.csv)

**Comment by ZylkaGreger** [comment]
![Throughput](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/1d1e017e-ba88-4c52-9fd3-6e6e2ba3f533)
![StartedVsFinished](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/ff728bcd-40e5-4e86-95d3-143b4838e677)
![CycleTime](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/6fda6af2-4202-435a-94d4-7b1f94662d6a)

**Comment by ZylkaGreger** [comment]
![WorkItemAge](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/69961700-1143-47ea-ab6e-82ab11e2a8c0)

The Work Item Age Scatterplot looks a bit weird as well - look at the dates at the bottom

**Comment by ZylkaGreger** [comment]
[config.json](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13940909/config.json)

**Comment by huserben** [comment]
@ZylkaGreger 
There was an issue with the Throughput Run Chart which I fixed in f1445068e3beb66a07556517ba8c3b3ecffae2cb

I believe the other charts were not recreated for you, so you saw data that was not matching your csv.

Can you try with the latest version (only `FlowMetricsService.py` has changed) and let me know if it now works (if yes, you can close the issue).

**Comment by ZylkaGreger** [comment]
With the new file, I'm getting:
C:\Users\PeterZylka\Desktop\FlowMetricsCSV-main>py .\FlowMetrics.py
Traceback (most recent call last):
  File "C:\Users\PeterZylka\Desktop\FlowMetricsCSV-main\FlowMetrics.py", line 4, in <module>
    from FlowMetricsService import FlowMetricsService
  File "C:\Users\PeterZylka\Desktop\FlowMetricsCSV-main\FlowMetricsService.py", line 103
    <title>FlowMetricsCSV/FlowMetricsService.py at main · LetPeopleWork/FlowMetricsCSV</title>
                                                        ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by ZylkaGreger** [comment]
Works as designed now - thanks for the fix
