### ISSUE TITLE
Started vs. closed graphic still not accurate

### ISSUE THREAD

**Issue by ZylkaGreger** [LetPeopleWork/FlowMetricsCSV#3]
I have a discrepancy in the data shown in the started vs. closed graphic.

According to the .csv file, I only had 21 started issues - in week 3 alone the graphic shows 30 started issues.
Same with the closed ones - there seem to be a difference for the ones closed in 2024 - CSV says 36 - graphic definitely shows more.

[Query_240116_1341.csv](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13950071/Query_240116_1341.csv)
[config.json](https://github.com/LetPeopleWork/FlowMetricsCSV/files/13950073/config.json)

Attaching config file and csv file

**Comment by ZylkaGreger** [comment]
![StartedVsFinished](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/155654042/a365e7f8-c231-47c2-a334-7d90a08dd443)

**Comment by huserben** [comment]
@ZylkaGreger fixed in 7488f060e78102732c7d582f65dc85a9f36fb1af - please verify and close or comment if it's not working yet.
