### ISSUE TITLE
Showing the Issue Links or IDs on the chart

### ISSUE THREAD

**Issue by aditk8149** [LetPeopleWork/FlowMetricsCSV#4]
Thank you so much for such an amazing and simple-to-use tool!

I was wondering if it will be feasible to show the Issue Links / IDs on the charts? There could be number of cases further, like clustering the number of ticket IDs which were closed on a given day and so on so forth, but wanted to know if this is something which will be done?

**Comment by huserben** [comment]
Hi @aditk8149 

We want to keep the tool simple. As it's creating pictures, there is no interactivity, so something like showing the id/title on hover is not possible.

Do you have any idea how you would like it visualized? We could try to show it next to the individual bubble, but depending on:
- How long the text is
- How many bubbles there are
- How clustered they are

It will potentially look messy.

However, if it's an optional setting, that might be ok.

**Comment by huserben** [comment]
How this could look like:
![IDs in Scatterplot](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/5486874/10ba40a5-07b9-4bf3-aaf7-3c9e7a296777)

For this there would be an extra setting "itemTitleColumn" in the _config.json_. If set, it points to the column in your csv that contains the "title" you want displayed. That can be anything you want, from ID, to a descriptive title to a link. That said, you can see that the space is limited.

What do you think @aditk8149 ? Will this be good enough? If yes, I'll push the changes and let you give it a try.

**Comment by aditk8149** [comment]
Thank you so much for your response @huserben! This is looking workable.

Right, the space is definitely limited, but I think it's much better than having simple dots. For knowing the outliers particularly, I had to do good switching between windows to confirm the ticket IDs and initiate conversation with the team. 😄 

About clustering, I am already seeing some combined numbers, making them difficult to understand. Is it workable to add ticketID + x, where x is count of remaining tickets which were closed on the same day.
- For instance - 44325 + 5 (and to know the 5 ticket IDs, I'll go CSV and find those IDs by the card 44325)

What do you think? Aside from clustering related stuff, if you want to push a build, I'm good to try it out.

**Comment by huserben** [comment]
Hi @aditk8149 

I've made some small adjustments with a library that tries to make sure the texts don't overlap. If you have big clusters, it won't work, but in general it should help. Now it looks like this:
![Clustering](https://github.com/LetPeopleWork/FlowMetricsCSV/assets/5486874/9b7a144a-bc3c-48a7-99cd-fc8ec32221f1)

I've pushed this version, if you download the latest version from the git repo you have this functionality. There is a new parameter in the _config.json_ that is called _itemTitleColumn_. When you set this to something (default is "ID"), it will take the value from this column and display it next to the bubble in the charts.

Anything else than this simple way of handling clusters is probably going beyond what we want/can do with the simple script.

Please let me know if the latest version now works for you.

**Comment by aditk8149** [comment]
Thank you! I will try this out and close the comment accordingly.

**Comment by aditk8149** [comment]
Tried this out, worked nice, thank you!
